groups:
- name: domain
  rules:
  - alert: DomainExpiring
    expr: domain_expiry_days < 30
    for: 0m
    labels:
      severity: warning
    annotations:
      description: 'Domain {{ $labels.domain }} will expire in less than 30 days'
      summary: '{{ $labels.domain }}: domain is expiring'

  - alert: DomainExpiring
    expr: domain_expiry_days < 7
    for: 0m
    labels:
      severity: page
    annotations:
      description: 'Domain {{ $labels.domain }} will expire in less than 7 days'
      summary: '{{ $labels.domain }}: domain is expiring'
